POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Novo Evento teste",
    "details": "Um evento para ...",
    "maximumAttendees": 1
}


###

POST http://localhost:3333/events/0d4ae03b-7609-49f1-8d48-43a881cccaa4/attendees
Content-Type: application/json

{
  "name": "Giselle Brasil",
  "email": "giselle5@gmail.com.br"
}


###

GET http://localhost:3333/events/0d4ae03b-7609-49f1-8d48-43a881cccaa4


### 


GET http://localhost:3333/attendees/4/badge